# Generated by Django 5.1.4 on 2025-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0015_user_bonus_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
    ]
