# Generated by Django 5.1.4 on 2026-01-17 16:02

import user_account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0018_alter_user_managers_contact_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_account.managers.CustomUserManager()),
            ],
        ),
    ]
