# Generated by Django 5.1.4 on 2025-01-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_user_orderitem_order_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
    ]
