# Generated by Django 5.1.4 on 2025-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bonus_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
