# Generated by Django 5.1.4 on 2025-04-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_bonus_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
