# Generated by Django 5.1.4 on 2025-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_bonus_points_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_743fca_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
    ]
