# Generated by Django 5.1.4 on 2025-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
            ),
        ),
    ]
