# Generated by Django 5.1.4 on 2026-01-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_deleted_order_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
