# Generated by Django 5.1.4 on 2026-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_deleted_orderitem_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='post_office',
            field=models.CharField(default='', max_length=250, verbose_name='post office'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='Odesa', max_length=250, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='e-mail'),
        ),
    ]
