from rest_framework import serializers
from parler_rest.serializers import TranslatableModelSerializer
from products.models.category import Category


class CategorySerializer(TranslatableModelSerializer):
    name = serializers.CharField(required=True, help_text="Category name")
    slug = serializers.SlugField(
        required=True,
        help_text="Category slug (autogenerated from name if not provided)"
    )

    class Meta:
        model = Category
        fields = ("id", "name", "slug")
        read_only_fields = ("id",)

    def validate_slug(self, value) -> str:
        instance = self.instance
        request = self.context.get('request')
        language = request.LANGUAGE_CODE if request is not None else 'en'

        query = Category.objects.filter(
            translations__slug=value,
            translations__language_code=language
        )

        if instance:
            query = query.exclude(pk=instance.pk)

        if query.exists():
            raise serializers.ValidationError("Category with this slug already exists.")

        return value

