from rest_framework import serializers
from parler_rest.serializers import TranslatableModelSerializer
from products.models.category import Category


class CategorySerializer(TranslatableModelSerializer):
    name = serializers.CharField(required=True, help_text="Category name")
    slug = serializers.SlugField(
        required=True,
        help_text="Category slug (autogenerated from name if not provided)"
    )

    class Meta:
        model = Category
        fields = ("id", "name", "slug")
        read_only_fields = ("id",)