# Generated by Django 5.1.4 on 2025-01-04 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_producttranslation_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "review", "verbose_name_plural": "reviews"},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-created_at"], name="products_re_created_351f12_idx"
            ),
        ),
    ]
