# Generated by Django 5.1.4 on 2025-02-05 17:19

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_review_options_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
