# Generated by Django 5.1.4 on 2025-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bonus_points",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
