# Generated by Django 5.1.4 on 2025-09-23 17:41

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import taggit.managers
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_quantity"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(
                default=True, help_text="Is product available for purchase"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bonus_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Bonus points earned from this product (non-negative)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Product category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when product was created"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.BooleanField(
                default=False, help_text="Is product on discount"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(help_text="Product image", upload_to="products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product price (minimum 0.01)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_with_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price (minimum 0.01)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Available quantity in stock"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Product tags for categorization",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when product was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="producttranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, help_text="Detailed product description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="producttranslation",
            name="name",
            field=models.CharField(help_text="Product name", max_length=200),
        ),
        migrations.AlterField(
            model_name="producttranslation",
            name="slug",
            field=models.SlugField(help_text="Product URL slug", max_length=200),
        ),
    ]
