# Generated by Django 5.1.4 on 2025-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0013_alter_product_available_alter_product_bonus_points_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_created_1360ea_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="products_re_created_351f12_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated",
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="name",
            field=models.CharField(help_text="Category name", max_length=200),
        ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="slug",
            field=models.SlugField(
                help_text="Category slug", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
                null=True,
            ),
        ),
    ]
