# Generated by Django 5.1.4 on 2025-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_remove_product_products_pr_created_1360ea_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when product was created",
            ),
        ),
    ]
