# Generated by Django 5.1.4 on 2026-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_deleted_category_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(help_text='Category slug', max_length=200),
        ),
    ]
