# Generated by Django 5.1.4 on 2026-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_categorytranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
