# Generated by Django 5.1.4 on 2025-02-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "coupon", "verbose_name_plural": "coupons"},
        ),
    ]
