# Generated by Django 5.1.4 on 2025-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "coupon", "verbose_name_plural": "coupons"},
        ),
        migrations.AddField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default="exit",
                help_text="Date and time when product was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when product was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Designates whether this coupon is active"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Unique coupon code (for example: SAVE20, SUMMER2024)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                help_text="Start date and time when the coupon becomes valid"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                help_text="End date and time when the coupon expires"
            ),
        ),
    ]
