# Generated by Django 5.1.4 on 2025-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_coupon_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Designates whether this coupon is active"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Unique coupon code (for example: SAVE20, SUMMER2024)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                help_text="Start date and time when the coupon becomes valid"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                help_text="End date and time when the coupon expires"
            ),
        ),
    ]
