# Generated by Django 5.1.4 on 2026-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_deleted_coupon_deleted_by_cascade'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Удаляем constraint, если существует
                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coupons_coupon_code_key') THEN
                        ALTER TABLE coupons_coupon DROP CONSTRAINT coupons_coupon_code_key;
                    END IF;
                    
                    -- Удаляем наш кастомный индекс, если создавали
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'coupons_coupon_code_active_unique') THEN
                        DROP INDEX coupons_coupon_code_active_unique;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Unique coupon code (for example: SAVE20, SUMMER2024)', max_length=50),
        ),
    ]
