name: micron_CI_CD

on:
  - push
  - pull_request

env:
  DJANGO_SETTINGS_MODULE: micron.settings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.9', '3.10', '3.10.7', '3.11.2' ]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check migrations
        run: |
          python micron/manage.py makemigrations
          python micron/manage.py migrate
          python micron/manage.py check
      - name: Run tests
        run: |
          python micron/manage.py test && flake8
